version: '3.9'

services:
    appservice:
        build: ./
        ports:
            - 5001:80
    website:
        image: nginx
        volumes:
            - ./AngularApp/dist:/etc/nginx/templates
        ports:
            - 5000:80
        environment:
            - NGINX_HOST=things.com
            - NGINX_PORT=80
        depends_on:
            - appservice
